language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql
before_script:
  - psql -c 'create database wayfarer;' -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD enthusiast;" -U postgres
  - npm run build
  - npm run migrate
script:
  - npm run test
after_success:
  - npm run coverage
